### ISSUE TITLE
failing when domain names are too short

### ISSUE THREAD

**Issue by smurp** [imgeraldalinio/certbot#1]
https://github.com/imgeraldalinio/certbot/blob/5b88b94102c0e60c1067f45d23c1499abdb28924/obtain-ssl-cert.sh#L18

I had to change this line to:
```
domain_name=$(printf "$DOMAINS" | grep -oE '[a-z0-9][a-z0-9-]{0,61}[a-z0-9](\w{2,}\.\w{2,3}\.\w{2,3}|\w{1,}\.\w{2,24})$')
```
to get it to recognize a three-letter long domain name like `doh.us`

**Comment by galinio** [comment]
@smurp thank you :)
